spring:
  application:
    name: saws-eureka-server

eureka:
  client:
    #是否将自己注册到Eureka Server,默认为true
    #由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: true
    ##是否从eureka server获取注册信息，如果不需要同步其他节点数据用false
    fetch-registry: false
    #设置服务注册中心的URL，用于client和server端交流
    server-url:
      defaultZone: http://localhost:7900/eureka/

server:
  port: 7900
